
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta http-equiv="refresh" content="10">
      <title>LMSensors Data</title>
      <style>
        body {
          font-family: Courier, monospace;
          background-color: #000000;
          color: #FFFFFF;
          margin: 0;
          height: 100vh;
          display: flex;
          justify-content: center;
          align-items: center;
        }
        .terminal {
          background-color: #000000;
          border: 3px solid #4CAF50;
          padding: 20px;
          border-radius: 5px;
          width: 80%;
          height: 80%;
          overflow: auto;
        }
        .file-content {
          color: #FFFFFF;
          font-family: Courier, monospace;
          white-space: pre-wrap;       /* css-3 */
          white-space: -moz-pre-wrap;  /* Mozilla, supported since 1999 */
          white-space: -pre-wrap;      /* Opera 4-6 */
          white-space: -o-pre-wrap;    /* Opera 7 */
          word-wrap: break-word;       /* Internet Explorer 5.5+ */
        }
        .file-title {
          color: #4CAF50;
          margin-top: 20px;
        }
      </style>
    </head>
    <body>
      <div class="terminal">
        <script>
          var fileNames = ["lmsensors-virt1.txt", "lmsensors-virt2.txt", "lmsensors-virt3.txt"];
          var shellPrompt = "root@lmsensors:~# cat ";

          fileNames.forEach(function(fileName){
            fetch(fileName)
            .then(response => response.text())
            .then(data => {
              var preElement = document.createElement("pre");
              preElement.className = "file-content";
              preElement.textContent = data;

              var h2Element = document.createElement("h2");
              h2Element.className = "file-title";
              h2Element.textContent = shellPrompt + fileName;

              var divElement = document.createElement("div");
              divElement.appendChild(h2Element);
              divElement.appendChild(preElement);

              document.querySelector(".terminal").appendChild(divElement);
            })
          });
        </script>
      </div>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmsensors-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmsensors-webserver
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lmsensors-webserver
    spec:
      containers:
        - name: webserver
          image: httpd:2.4
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: data-volume
            - mountPath: /usr/local/apache2/htdocs/index.html
              name: index-html
              subPath: index.html
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-lmsensors
      - name: index-html
        configMap:
          name: index-html
---
apiVersion: v1
kind: Service
metadata:
  name: lmsensors-webserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: lmsensors-webserver
